backend:
  name: git-gateway
  branch: main
  repo: JorgeQSJunior/JorgeQSJrADV

site_url: https://enchanting-mooncake-b509d7.netlify.app
logo_url: /favicon.ico

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Corpo", name: "body", widget: "markdown" }

  - name: "sumulas"
    label: "Súmulas e Jurisprudência"
    folder: "sumulas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Assunto", name: "assunto", widget: "string" }
      - { label: "Referência", name: "referencia", widget: "string" }
      - { label: "Corpo", name: "body", widget: "markdown" }
